# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [2]:
import numpy as np

a=np.arange(11)
a[2:6]=a[2:6]*(-1)
print(a)

[ 0  1 -2 -3 -4 -5  6  7  8  9 10]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [18]:
A = np.random.rand(3, 6)

print(A)
check=A>0.5
check[check==True].size

[[0.99182813 0.30525587 0.49510244 0.3404975  0.43892291 0.35120265]
 [0.20754346 0.32365104 0.38148566 0.32597889 0.09272246 0.39682308]
 [0.32376289 0.16619997 0.35812095 0.69201761 0.9225314  0.32418868]]


3