In [3]:
import numpy as np

a=np.random.randint(10,size=15).reshape(3,5)
print(a)
print(list(a))
print(a.tolist())

'''
Ans 1: python內建之list函式僅可回傳第一層資料，而numpy之tolist()方法可回傳一巢狀陣列
'''

[[1 9 3 0 2]
 [5 9 8 1 4]
 [8 3 7 3 0]]
[array([1, 9, 3, 0, 2]), array([5, 9, 8, 1, 4]), array([8, 3, 7, 3, 0])]
[[1, 9, 3, 0, 2], [5, 9, 8, 1, 4], [8, 3, 7, 3, 0]]


In [14]:
a = np.random.randint(10, size=6) 
b = np.random.randint(10, size=(3,4)) 
c = np.random.randint(10, size=(2,3,2)) 

print(a.ndim)     #dimension of the array
print(a.shape)    #size of each dimension of the array
print(a.size)     #total counts of elements within the array
print(a.dtype)    #the data type of elements in the array
print(a.itemsize) #the occupied spaces of elements in the array
print(len(a))     #the length of the array, in this case, it is the same as the size of the array
print(type(a))    #return the name of the data structure, in this case, of course, is 'numpy.ndarray'

print('\n')
print(b.ndim)     
print(b.shape)    
print(b.size) 
print(b.dtype)  
print(b.itemsize) 
print(len(b))     
#it seems in cases of 2-D array, the function returns the length of the array of one of the dimension(longest one)
print(type(b))

print('\n')
print(c.ndim)     
print(c.shape)    
print(c.size) 
print(c.dtype)  
print(c.itemsize) 
print(len(c))     
print(type(c))

1
(6,)
6
int32
4
6
<class 'numpy.ndarray'>


2
(3, 4)
12
int32
4
3
<class 'numpy.ndarray'>


3
(2, 3, 2)
12
int32
4
2
<class 'numpy.ndarray'>


In [17]:
a=np.random.randint(10,size=15).reshape(3,5)

A=[]
for i in range(3):
    A.append(list(a[i,:]))
    
print(A)

[[9, 4, 5, 1, 3], [9, 8, 0, 8, 2], [0, 6, 8, 4, 5]]
